packages:
  - "apps/*"
  - "apps/workers/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - argon2
  - esbuild
  - prisma
  - unrs-resolver

allowBuilds:
  '@google/genai': true
  "@prisma/client": true
  "@prisma/engines": true
  argon2: true
  esbuild: true
  prisma: true
  protobufjs: true
  unrs-resolver: true
