export const semanticColors = {
  background: 'hsl(var(--background))',
  foreground: 'hsl(var(--foreground))',
  card: 'hsl(var(--card))',
  muted: 'hsl(var(--muted))',
  border: 'hsl(var(--border))',
  primary: 'hsl(var(--primary))',
  success: 'hsl(var(--success))',
  warning: 'hsl(var(--warning))',
  danger: 'hsl(var(--destructive))',
  info: 'hsl(var(--info))',
  pastel: {
    blue: 'hsl(var(--pastel-blue))',
    mint: 'hsl(var(--pastel-mint))',
    sand: 'hsl(var(--pastel-sand))',
    lavender: 'hsl(var(--pastel-lavender))',
    rose: 'hsl(var(--pastel-rose))',
    yellow: 'hsl(var(--pastel-yellow))',
    cyan: 'hsl(var(--pastel-cyan))',
    peach: 'hsl(var(--pastel-peach))',
  },
} as const;

export const statusToneMap = {
  ACTIVE: 'success',
  READY: 'success',
  COMPLETED: 'success',
  SOLVED: 'success',
  ACCEPTED: 'success',
  PASSED: 'success',
  PUBLISHED: 'success',
  SUCCEEDED: 'success',
  DRAFT: 'neutral',
  NOT_STARTED: 'neutral',
  QUEUED: 'info',
  PROCESSING: 'info',
  RUNNING: 'info',
  IN_PROGRESS: 'info',
  UPLOADING: 'info',
  AWAITING_REVIEW: 'warning',
  ATTEMPTED: 'warning',
  SUSPENDED: 'danger',
  DISABLED: 'danger',
  ARCHIVED: 'danger',
  FAILED: 'danger',
  ERROR: 'danger',
  TIMED_OUT: 'danger',
  REJECTED: 'danger',
} as const;
