# HTTP -> HTTPS
server {
    listen 80;
    server_name codingtime.click www.codingtime.click;

    return 301 https://codingtime.click$request_uri;
}

# Main HTTPS site
server {
    listen 443 ssl;
    server_name codingtime.click;

    ssl_certificate /etc/letsencrypt/live/codingtime.click/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/codingtime.click/privkey.pem;

    client_max_body_size 20m;

    resolver 127.0.0.11 valid=10s ipv6=off;

    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_set_header Range $http_range;
    proxy_set_header If-Range $http_if_range;

    proxy_read_timeout 120s;
    proxy_send_timeout 120s;

    location /api/ {
        set $backend_upstream http://backend:4000;
        proxy_pass $backend_upstream;
    }

    location / {
        set $frontend_upstream http://frontend:3000;
        proxy_pass $frontend_upstream;
    }
}

# www HTTPS -> main domain
server {
    listen 443 ssl;
    server_name www.codingtime.click;

    ssl_certificate /etc/letsencrypt/live/codingtime.click/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/codingtime.click/privkey.pem;

    return 301 https://codingtime.click$request_uri;
}

server {
    listen 443 ssl;
    server_name storage.codingtime.click;

    ssl_certificate /etc/letsencrypt/live/storage.codingtime.click/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/storage.codingtime.click/privkey.pem;

    client_max_body_size 3g;

    resolver 127.0.0.11 valid=10s ipv6=off;

    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;

    proxy_read_timeout 120s;
    proxy_send_timeout 120s;

    location / {
    set $minio_upstream http://minio:9000;

    proxy_request_buffering off;
    proxy_buffering off;

    proxy_pass $minio_upstream;
    }
}

server {
    listen 80;
    server_name storage.codingtime.click;

    return 301 https://storage.codingtime.click$request_uri;
}
