export {
  PRACTICE_FUNCTION_ADAPTER_PATH,
  PRACTICE_FUNCTION_ADAPTER_SOURCE,
  PRACTICE_GENERATOR_ORACLE_ADAPTER_PATH,
  PRACTICE_GENERATOR_ORACLE_ADAPTER_SOURCE,
  PRACTICE_ORACLE_BATCH_ADAPTER_PATH,
  PRACTICE_ORACLE_BATCH_ADAPTER_SOURCE,
} from '@codesync/shared';
